// <auto-generated />
using System;
using AcadEvents.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcadEvents.Migrations
{
    [DbContext(typeof(AcadEventsDbContext))]
    [Migration("20251118115008_RemoveSubmissaoTrilhaRelationship")]
    partial class RemoveSubmissaoTrilhaRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcadEvents.Models.ArquivoSubmissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SubmissaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Tamanho")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubmissaoId");

                    b.ToTable("ArquivosSubmissao");
                });

            modelBuilder.Entity("AcadEvents.Models.Avaliacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AvaliadorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Confidencial")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<double>("NotaGeral")
                        .HasColumnType("float");

                    b.Property<double>("NotaMetodologia")
                        .HasColumnType("float");

                    b.Property<double>("NotaOriginalidade")
                        .HasColumnType("float");

                    b.Property<double>("NotaRedacao")
                        .HasColumnType("float");

                    b.Property<double>("NotaRelevancia")
                        .HasColumnType("float");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SubmissaoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AvaliadorId");

                    b.HasIndex("SubmissaoId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("AcadEvents.Models.ComiteCientifico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("ComitesCientificos");
                });

            modelBuilder.Entity("AcadEvents.Models.ConfiguracaoEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AvaliacaoDuploCego")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroAvaliadoresPorSubmissao")
                        .HasColumnType("int");

                    b.Property<bool>("PermiteResubmissao")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PrazoAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PrazoSubmissao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesEvento");
                });

            modelBuilder.Entity("AcadEvents.Models.ConviteAvaliacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Aceito")
                        .HasColumnType("bit");

                    b.Property<long>("AvaliadorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataConvite")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRecusa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrazoAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubmissaoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AvaliadorId");

                    b.HasIndex("SubmissaoId");

                    b.ToTable("ConvitesAvaliacao");
                });

            modelBuilder.Entity("AcadEvents.Models.DOI", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Valido")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DOIs");
                });

            modelBuilder.Entity("AcadEvents.Models.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ConfiguracaoEventoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracaoEventoId")
                        .IsUnique();

                    b.HasIndex("Nome");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("AcadEvents.Models.HistoricoEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistoricosEvento");
                });

            modelBuilder.Entity("AcadEvents.Models.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("AcadEvents.Models.PerfilORCID", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrcidId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publicacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Verificado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfisORCID");
                });

            modelBuilder.Entity("AcadEvents.Models.Referencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Autores")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DOIId")
                        .HasColumnType("bigint");

                    b.Property<string>("FormatoABNT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paginas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publicacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SubmissaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DOIId");

                    b.HasIndex("SubmissaoId");

                    b.ToTable("Referencias");
                });

            modelBuilder.Entity("AcadEvents.Models.Sessao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moderador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrilhaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrilhaId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("AcadEvents.Models.Submissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AutorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DOIId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataSubmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaModificacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Formato")
                        .HasColumnType("int");

                    b.Property<string>("PalavrasChave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SessaoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrilhaTematicaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("DOIId")
                        .IsUnique()
                        .HasFilter("[DOIId] IS NOT NULL");

                    b.HasIndex("SessaoId");

                    b.HasIndex("TrilhaTematicaId");

                    b.ToTable("Submissoes");
                });

            modelBuilder.Entity("AcadEvents.Models.Trilha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Coordenador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint");

                    b.Property<int>("LimiteSubmissoes")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Trilhas");
                });

            modelBuilder.Entity("AcadEvents.Models.TrilhaTematica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PalavrasChave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrilhaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrilhaId");

                    b.ToTable("TrilhasTematicas");
                });

            modelBuilder.Entity("AcadEvents.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AvaliadorComiteCientifico", b =>
                {
                    b.Property<long>("ComitesId")
                        .HasColumnType("bigint");

                    b.Property<long>("MembrosAvaliadoresId")
                        .HasColumnType("bigint");

                    b.HasKey("ComitesId", "MembrosAvaliadoresId");

                    b.HasIndex("MembrosAvaliadoresId");

                    b.ToTable("ComiteAvaliador", (string)null);
                });

            modelBuilder.Entity("ComiteCientificoOrganizador", b =>
                {
                    b.Property<long>("ComitesCoordenadosId")
                        .HasColumnType("bigint");

                    b.Property<long>("CoordenadoresId")
                        .HasColumnType("bigint");

                    b.HasKey("ComitesCoordenadosId", "CoordenadoresId");

                    b.HasIndex("CoordenadoresId");

                    b.ToTable("ComiteOrganizador", (string)null);
                });

            modelBuilder.Entity("EventoOrganizador", b =>
                {
                    b.Property<long>("EventosOrganizadosId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizadoresId")
                        .HasColumnType("bigint");

                    b.HasKey("EventosOrganizadosId", "OrganizadoresId");

                    b.HasIndex("OrganizadoresId");

                    b.ToTable("EventoOrganizador", (string)null);
                });

            modelBuilder.Entity("AcadEvents.Models.Autor", b =>
                {
                    b.HasBaseType("AcadEvents.Models.Usuario");

                    b.Property<string>("AreaAtuacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lattes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Autores", (string)null);
                });

            modelBuilder.Entity("AcadEvents.Models.Avaliador", b =>
                {
                    b.HasBaseType("AcadEvents.Models.Usuario");

                    b.Property<bool>("Disponibilidade")
                        .HasColumnType("bit");

                    b.Property<string>("Especialidades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroAvaliacoes")
                        .HasColumnType("int");

                    b.ToTable("Avaliadores", (string)null);
                });

            modelBuilder.Entity("AcadEvents.Models.Organizador", b =>
                {
                    b.HasBaseType("AcadEvents.Models.Usuario");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Organizadores", (string)null);
                });

            modelBuilder.Entity("AcadEvents.Models.ArquivoSubmissao", b =>
                {
                    b.HasOne("AcadEvents.Models.Submissao", "Submissao")
                        .WithMany("Arquivos")
                        .HasForeignKey("SubmissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submissao");
                });

            modelBuilder.Entity("AcadEvents.Models.Avaliacao", b =>
                {
                    b.HasOne("AcadEvents.Models.Avaliador", "Avaliador")
                        .WithMany("AvaliacoesRealizadas")
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AcadEvents.Models.Submissao", "Submissao")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("SubmissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliador");

                    b.Navigation("Submissao");
                });

            modelBuilder.Entity("AcadEvents.Models.ComiteCientifico", b =>
                {
                    b.HasOne("AcadEvents.Models.Evento", "Evento")
                        .WithMany("Comites")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AcadEvents.Models.ConviteAvaliacao", b =>
                {
                    b.HasOne("AcadEvents.Models.Avaliador", "Avaliador")
                        .WithMany("ConvitesRecebidos")
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AcadEvents.Models.Submissao", "Submissao")
                        .WithMany("Convites")
                        .HasForeignKey("SubmissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliador");

                    b.Navigation("Submissao");
                });

            modelBuilder.Entity("AcadEvents.Models.Evento", b =>
                {
                    b.HasOne("AcadEvents.Models.ConfiguracaoEvento", "Configuracao")
                        .WithOne("Evento")
                        .HasForeignKey("AcadEvents.Models.Evento", "ConfiguracaoEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuracao");
                });

            modelBuilder.Entity("AcadEvents.Models.HistoricoEvento", b =>
                {
                    b.HasOne("AcadEvents.Models.Evento", "Evento")
                        .WithMany("Historico")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcadEvents.Models.Usuario", "Usuario")
                        .WithMany("Historicos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcadEvents.Models.Notificacao", b =>
                {
                    b.HasOne("AcadEvents.Models.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcadEvents.Models.PerfilORCID", b =>
                {
                    b.HasOne("AcadEvents.Models.Usuario", "Usuario")
                        .WithOne("PerfilORCID")
                        .HasForeignKey("AcadEvents.Models.PerfilORCID", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcadEvents.Models.Referencia", b =>
                {
                    b.HasOne("AcadEvents.Models.DOI", "DOI")
                        .WithMany("Referencias")
                        .HasForeignKey("DOIId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AcadEvents.Models.Submissao", "Submissao")
                        .WithMany("Referencias")
                        .HasForeignKey("SubmissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DOI");

                    b.Navigation("Submissao");
                });

            modelBuilder.Entity("AcadEvents.Models.Sessao", b =>
                {
                    b.HasOne("AcadEvents.Models.Trilha", "Trilha")
                        .WithMany("Sessoes")
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("AcadEvents.Models.Submissao", b =>
                {
                    b.HasOne("AcadEvents.Models.Autor", "Autor")
                        .WithMany("Submissoes")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AcadEvents.Models.DOI", "DOI")
                        .WithOne("Submissao")
                        .HasForeignKey("AcadEvents.Models.Submissao", "DOIId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AcadEvents.Models.Sessao", "Sessao")
                        .WithMany("SubmissoesApresentadas")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AcadEvents.Models.TrilhaTematica", "TrilhaTematica")
                        .WithMany("Submissoes")
                        .HasForeignKey("TrilhaTematicaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("DOI");

                    b.Navigation("Sessao");

                    b.Navigation("TrilhaTematica");
                });

            modelBuilder.Entity("AcadEvents.Models.Trilha", b =>
                {
                    b.HasOne("AcadEvents.Models.Evento", "Evento")
                        .WithMany("Trilhas")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AcadEvents.Models.TrilhaTematica", b =>
                {
                    b.HasOne("AcadEvents.Models.Trilha", "Trilha")
                        .WithMany("Tematicas")
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("AvaliadorComiteCientifico", b =>
                {
                    b.HasOne("AcadEvents.Models.ComiteCientifico", null)
                        .WithMany()
                        .HasForeignKey("ComitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcadEvents.Models.Avaliador", null)
                        .WithMany()
                        .HasForeignKey("MembrosAvaliadoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComiteCientificoOrganizador", b =>
                {
                    b.HasOne("AcadEvents.Models.ComiteCientifico", null)
                        .WithMany()
                        .HasForeignKey("ComitesCoordenadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcadEvents.Models.Organizador", null)
                        .WithMany()
                        .HasForeignKey("CoordenadoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventoOrganizador", b =>
                {
                    b.HasOne("AcadEvents.Models.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventosOrganizadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcadEvents.Models.Organizador", null)
                        .WithMany()
                        .HasForeignKey("OrganizadoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcadEvents.Models.Autor", b =>
                {
                    b.HasOne("AcadEvents.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("AcadEvents.Models.Autor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcadEvents.Models.Avaliador", b =>
                {
                    b.HasOne("AcadEvents.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("AcadEvents.Models.Avaliador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcadEvents.Models.Organizador", b =>
                {
                    b.HasOne("AcadEvents.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("AcadEvents.Models.Organizador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcadEvents.Models.ConfiguracaoEvento", b =>
                {
                    b.Navigation("Evento")
                        .IsRequired();
                });

            modelBuilder.Entity("AcadEvents.Models.DOI", b =>
                {
                    b.Navigation("Referencias");

                    b.Navigation("Submissao");
                });

            modelBuilder.Entity("AcadEvents.Models.Evento", b =>
                {
                    b.Navigation("Comites");

                    b.Navigation("Historico");

                    b.Navigation("Trilhas");
                });

            modelBuilder.Entity("AcadEvents.Models.Sessao", b =>
                {
                    b.Navigation("SubmissoesApresentadas");
                });

            modelBuilder.Entity("AcadEvents.Models.Submissao", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Convites");

                    b.Navigation("Referencias");
                });

            modelBuilder.Entity("AcadEvents.Models.Trilha", b =>
                {
                    b.Navigation("Sessoes");

                    b.Navigation("Tematicas");
                });

            modelBuilder.Entity("AcadEvents.Models.TrilhaTematica", b =>
                {
                    b.Navigation("Submissoes");
                });

            modelBuilder.Entity("AcadEvents.Models.Usuario", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("Notificacoes");

                    b.Navigation("PerfilORCID");
                });

            modelBuilder.Entity("AcadEvents.Models.Autor", b =>
                {
                    b.Navigation("Submissoes");
                });

            modelBuilder.Entity("AcadEvents.Models.Avaliador", b =>
                {
                    b.Navigation("AvaliacoesRealizadas");

                    b.Navigation("ConvitesRecebidos");
                });
#pragma warning restore 612, 618
        }
    }
}
